now() {
    printf "%s" "$(date -u +%FT%H:%M:%SZ)"
}

alias l="ls --color -FlGh"
alias ll="ls --color -FlaGh"
alias fd="fdfind"
alias gst="git status"

export CDPATH=".:$HOME:$HOME/Projects"

# ble - https://github.com/akinomyoga/ble.sh
BLE_PATH="$HOME/.local/share/blesh"
if [ -d "$BLE_PATH" ]; then
    source -- "$BLE_PATH/ble.sh"
    ble-bind -m emacs -f 'M-C-?' 'kill-backward-uword'
fi

# fnm
FNM_PATH="$HOME/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
    export PATH="$FNM_PATH:$PATH"
    eval "$(fnm env --use-on-cd --shell bash)"
fi

# Go
if command -v go >/dev/null; then
    export GOPATH="$HOME/.local/share/go"
    export PATH="$GOPATH/bin:$PATH"
fi

# odin
if [ -d "$HOME/.local/share/odin/bin" ]; then
    export PATH="$HOME/.local/share/odin/bin:$PATH"
fi

# starship - https://github.com/starship/starship
STARSHIP_PATH="/usr/local/bin/starship"
if [ -f "$STARSHIP_PATH" ]; then
    eval "$(starship init bash)"
fi
